name: 'Run common python lints'
description: 'Runs black and flake8'
author: 'bobby.ward@inmar.com'
inputs:
  directories:
    description: 'Comma separated list of directories to check'
    default: '.'
  black:
    description: 'Run black'
    default: 'true'
  flake8:
    description: 'Run flake8'
    default: 'true'
runs:
  using: 'node12'
  main: 'lib/main.js'
